### ISSUE TITLE
Download link for pyrosetta is dead

### ISSUE THREAD

**Issue by yakomaxa** [naokob/ColabGCNdesign#3]
Currently, the download link for pyrosetta is hard-corded as 
`https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.MinSizeRel.python37.linux/PyRosetta4.MinSizeRel.python37.linux.release-316.tar.bz2`
but this link is now dead.

So we need to replace this to the one available today such as
`https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.MinSizeRel.python37.linux/PyRosetta4.MinSizeRel.python37.linux.release-328.tar.bz2`

**Comment by naokob** [comment]
Thank you very much. I have corrected it as per your advice.
